alias ll="ls -al"
alias l="ll"
alias ..="cd .."
alias sshr="ssh -l root"
alias r="ruby"
alias gp="git pull"
alias gst="git status"
alias delSVN="find . -name ".svn" -exec rm -rf {} \;"
alias tf="tail -f"
alias sshX11="ssh -X -C -c blowfish-cbc,arcfour"
alias gv="UBUNTU_MENUPROXY= gvim"
alias gvbr="gv /home/$(whoami)/.bashrc"
alias gval="gv /home/$(whoami)/dotfiles/aliases.sh"
