alias ll="ls -al"
alias l="ll"
alias ..="cd .."
alias sshr="ssh -l root"
alias r="ruby"
alias g="git pull"
alias delSVN="find . -name ".svn" -exec rm -rf {} \;"
alias tf="tail -f"
alias sshX11="ssh -X -C -c blowfish-cbc,arcfour"
alias gv="UBUNTU_MENUPROXY= gvim"
alias gvbr="gv /home/benny/.bashrc"
